export type MrCompletion = {
  token: string;
  label: string;
  description: string;
  marathi: string;
  insertText: string;
  category: string;
};

export const mrCompletions: MrCompletion[] = [
  {
    token: 'ank',
    label: 'ank',
    description: 'Integer type',
    marathi: 'पूर्णांक प्रकार',
    insertText: 'ank ${name} = ${value};',
    category: 'type',
  },
  {
    token: 'he',
    label: 'he',
    description: 'Scalar / singular declaration',
    marathi: 'एकच मूल्य घोषित करते',
    insertText: 'he ${type} ${name} = ${value};',
    category: 'modifier',
  },
  {
    token: 'te',
    label: 'te',
    description: 'Collection / array declaration',
    marathi: 'संग्रह किंवा अॅरे घोषित करते',
    insertText: 'te ${type} ${name};',
    category: 'modifier',
  },
  {
    token: 'ahe',
    label: 'ahe',
    description: 'Immutable / constant declaration',
    marathi: 'अपरिवर्तनीय मूल्य',
    insertText: 'he ank ${name} ahe ${value};',
    category: 'modifier',
  },
  {
    token: 'jar',
    label: 'jar',
    description: 'If condition',
    marathi: 'अट खरी असल्यास',
    insertText: 'jar (${condition}) {\n    ${body}\n}',
    category: 'control',
  },
  {
    token: 'nahitar',
    label: 'nahitar',
    description: 'Else-if condition',
    marathi: 'दुसरी अट तपासते',
    insertText: 'nahitar (${condition}) {\n    ${body}\n}',
    category: 'control',
  },
  {
    token: 'anyatha',
    label: 'anyatha',
    description: 'Else block',
    marathi: 'अन्यथा हा भाग चालतो',
    insertText: 'anyatha {\n    ${body}\n}',
    category: 'control',
  },
  {
    token: 'jovar',
    label: 'jovar',
    description: 'While loop',
    marathi: 'अट खरी असेपर्यंत पुन्हा चालते',
    insertText: 'jovar (${condition}) {\n    ${body}\n}',
    category: 'flow',
  },
  {
    token: 'pratyek',
    label: 'pratyek',
    description: 'For loop',
    marathi: 'ठरावीक पद्धतीने पुनरावृत्ती',
    insertText: 'pratyek (${initialization}; ${condition}; ${increment}) {\n    ${body}\n}',
    category: 'flow',
  },
  {
    token: 'thamba',
    label: 'thamba',
    description: 'Break out of the current loop',
    marathi: 'सध्याची पुनरावृत्ती थांबवते',
    insertText: 'thamba;',
    category: 'flow',
  },
  {
    token: 'pudhe',
    label: 'pudhe',
    description: 'Continue to the next iteration',
    marathi: 'पुढच्या पुनरावृत्तीकडे जाते',
    insertText: 'pudhe;',
    category: 'flow',
  },
  {
    token: 'karya',
    label: 'karya',
    description: 'Declare a function',
    marathi: 'कार्य घोषित करते',
    insertText: '${returnType} karya(${parameters}) {\n    ${body}\n}',
    category: 'function',
  },
  {
    token: 'nirank',
    label: 'nirank',
    description: 'Void / no-return type',
    marathi: 'मूल्य परत न करणारे कार्य',
    insertText: 'nirank karya(${parameters}) {\n    ${body}\n}',
    category: 'type',
  },
  {
    token: 'partav',
    label: 'partav',
    description: 'Return a value from a function',
    marathi: 'कार्यातून मूल्य परत करते',
    insertText: 'partav ${value};',
    category: 'flow',
  },
  {
    token: 'leeh',
    label: 'leeh',
    description: 'Print a value',
    marathi: 'मूल्य उत्पादनात दाखवते',
    insertText: 'leeh(${value});',
    category: 'builtin',
  },
  {
    token: 'shevti',
    label: 'shevti',
    description: 'Terminate program execution',
    marathi: 'कार्यक्रम स्पष्ट समाप्ती क्रमांकासह थांबवते',
    insertText: 'shevti(${value});',
    category: 'builtin',
  },
  {
    token: 'khare',
    label: 'khare',
    description: 'Boolean true',
    marathi: 'खरे बूलियन मूल्य',
    insertText: 'khare',
    category: 'constant',
  },
  {
    token: 'khote',
    label: 'khote',
    description: 'Boolean false',
    marathi: 'खोटे बूलियन मूल्य',
    insertText: 'khote',
    category: 'constant',
  },
  {
    token: 'ani',
    label: 'ani',
    description: 'Logical AND',
    marathi: 'तार्किक आणि',
    insertText: 'ani',
    category: 'operator',
  },
  {
    token: 'va',
    label: 'va',
    description: 'Logical OR',
    marathi: 'तार्किक किंवा',
    insertText: 'va',
    category: 'operator',
  },
];